name: jump_jump
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.2
  firebase_core: ^3.1.1
  flame: ^1.15.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Mighty
      fonts:
        - asset: assets/fonts/MightySouly-lxggD.ttf
  assets:
    - assets/images/
    - assets/audio/